spring:
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/ruoyi_rag?authSource=admin

  ai:
    openai:
      # openai: gpt-3.5-turbo gpt-4o
      base-url: https://api.xty.app
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 0.7
    ollama:
      # ollama config: qwen2:7b  llama3:latest
      base-url: http://localhost:11434
      embedding:
        model: qllama/bge-small-zh-v1.5
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
      chat:
        options:
          model: glm-4-air
          temperature: 0.7
      embedding:
        options:
          model: embedding-3
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        initialize-schema: true
        collection-name: rag
# 如果需要使用 MCP 服务，取消注释以下配置
#    mcp:
#      client:
#        enabled: true
#        name: spring-ai-mcp-client
#        type: ASYNC
#        sse:
#          connections:
#            server1:
#             url: https://mcp.amap.com
#             sse-endpoint: /sse?key=${GAODE_API_KEY}
#            server2:
#              url: http://localhost:9055
#              sse-endpoint: /sse
#        stdio:
#          servers-configuration: classpath:mcp-server.json




# SearXNG配置
searxng:
  host: http://localhost:8080
  timeout: 5000