version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: dev-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    container_name: dev-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes

  # redis2:
  #   image: redis:7
  #   container_name: dev-redis2
  #   restart: always
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - ./redis2/data:/data
  #   command: redis-server --appendonly yes

  # redis3:
  #   image: redis:7
  #   container_name: dev-redis3
  #   restart: always
  #   ports:
  #     - "6381:6379"
  #   volumes:
  #     - ./redis3/data:/data
  #   command: redis-server --appendonly yes

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: dev-nacos
    restart: always
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
      TZ: Asia/Shanghai
    volumes:
      - ./nacos/data:/home/nacos/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dev-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: dev-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  nginx:
    image: nginx:1.26-alpine
    container_name: dev-nginx
    restart: always
    ports:
      - "8088:8080" 
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
  
  mongodb:
    image: mongo:7
    container_name: dev-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: dev_db
      TZ: Asia/Shanghai
    volumes:
      - ./mongodb/data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.2.1
    container_name: dev-qdrant
    restart: always
    ports:
      - "6334:6334"   # 将容器的 6334 端口映射到主机的 6334 端口
    volumes:
      - ./qdrant/data:/qdrant/storage  # 持久化存储数据